[tool.poetry]
name = "tap-mysql"
version = "0.0.1"
description = "`tap-mysql` is a Singer tap for mysql, built with the Meltano Singer SDK."
authors = ["Meltano Team and Contributors <hello@meltano.com>"]
maintainers = ["Meltano Team and Contributors <hello@meltano.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://meltano.com"
repository = "https://github.com/meltanolabs/tap-mysql"
keywords = [
    "MySQL",
    "Vitess",
    "PlanetScale",
    "Singer",
    "ELT",
    "Meltano",
    "Meltano SDK",
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
]
packages = [
    { include = "tap_mysql" }
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
fs-s3fs = { version = "==1.1.1", optional = true }
sqlalchemy = "^2.0.36"
sshtunnel = "^0.4.0"
paramiko = "^3.5.0"
meltano-db = {git = "https://github.com/nektcom/nekt-meltano-db-helper.git", rev = "main"}
pymysql = "^1.1.1"
mysql-replication = "^1.0.9"
python-dateutil = "^2.9.0.post0"
nekt-singer-sdk = {git = "https://github.com/olbycom/singer-sdk.git", rev = "v0.2.4"}
[tool.poetry.group.dev.dependencies]
pytest = ">=8"
hypothesis = "^6.122.4"

[tool.poetry.extras]
s3 = ["fs-s3fs"]

[tool.pytest.ini_options]
addopts = '--durations=10'

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
plugins = "sqlmypy"

[tool.ruff]
line-length = 160
exclude = ["**/migrations/**"]

[tool.ruff.lint]
ignore = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "D104",  # Missing docstring in public package
    "F401",  # Imported but unused; consider removing, adding to `__all__`, or using a redundant alias
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-mysql = 'tap_mysql.tap:TapMySQL.cli'
